antojito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # Auth
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    # Auth
    path('singup', views.singup, name="singup"),
    path('logout', views.logout, name="logout"),
    path('login', views.login, name="login"),
    path('accounts/login/', views.login, name="redirectToLogin"),
    # Pages
    path('', views.home, name="home"),
    path('home', views.ppage, name="ppage"),
    path('payment', views.payment, name="payment"),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.hashers import make_password
# Create your models here.


class ArepadeHuevo(models.Model):
    # Choices
    FTMN = models.TextChoices(
        'Tamano Comida', 'Pequeno Mediano Grande')
    DSPNL = models.TextChoices('Disponibilidad', 'Si No')

    Id = models.AutoField(primary_key=True)
    name = models.CharField(default="Arepa de Huevo", max_length=20)
    Imagen = models.ImageField(upload_to='shop/media', blank=False, null=True)
    Tamano = models.CharField(
        max_length=10, choices=FTMN.choices, blank=False, null=True)
    PrecioU = models.CharField(
        max_length=5, blank=False, null=True)
    Disponible = models.CharField(
        max_length=5, choices=DSPNL.choices, blank=False, null=True)
    Created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = ("ArepadeHuevo")
        verbose_name_plural = ("ArepadeHuevos")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ArepadeHuevo_detail", kwargs={"pk": self.pk})


class Carimanola(models.Model):

    # Choices
    FTMN = models.TextChoices(
        'Tamano Comida', 'Pequeno Mediano Grande')
    DSPNL = models.TextChoices('Disponibilidad', 'Si No')

    Id = models.AutoField(primary_key=True)
    name = models.CharField(default="Carimanola", max_length=20)
    Imagen = models.ImageField(upload_to='shop/media', blank=False, null=True)
    Tamano = models.CharField(
        max_length=10, choices=FTMN.choices, blank=False, null=True)
    PrecioU = models.CharField(
        max_length=5, blank=False, null=True)
    Disponible = models.CharField(
        max_length=5, choices=DSPNL.choices, blank=False, null=True)
    Created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = ("Carimanola")
        verbose_name_plural = ("Carimanolas")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Carimanola_detail", kwargs={"pk": self.pk})


class Empanada(models.Model):

    # Choices
    FTMN = models.TextChoices(
        'Tamano Comida', 'Pequeno Mediano Grande')
    DSPNL = models.TextChoices('Disponibilidad', 'Si No')

    Id = models.AutoField(primary_key=True)
    name = models.CharField(default="Empanada", max_length=20)
    Imagen = models.ImageField(upload_to='shop/media', blank=False, null=True)
    Tamano = models.CharField(
        max_length=10, choices=FTMN.choices, blank=False, null=True)
    PrecioU = models.CharField(
        max_length=5, blank=False, null=True)
    Disponible = models.CharField(
        max_length=5, choices=DSPNL.choices, blank=False, null=True)
    Created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = ("Empanada")
        verbose_name_plural = ("Empanadas")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Empanada_detail", kwargs={"pk": self.pk})


class Salchipapa(models.Model):

    # Choices
    FTMN = models.TextChoices(
        'Tamano Comida', 'Pequeno Mediano Grande')
    DSPNL = models.TextChoices('Disponibilidad', 'Si No')

    Id = models.AutoField(primary_key=True)
    name = models.CharField(default="Salchipapa", max_length=20)
    Imagen = models.ImageField(upload_to='shop/media', blank=False, null=True)
    Tamano = models.CharField(
        max_length=10, choices=FTMN.choices, blank=False, null=True)
    PrecioU = models.CharField(
        max_length=5, blank=False, null=True)
    Disponible = models.CharField(
        max_length=5, choices=DSPNL.choices, blank=False, null=True)
    Created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = ("Salchipapa")
        verbose_name_plural = ("Salchipapas")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Salchipapa_detail", kwargs={"pk": self.pk})


class Bollo(models.Model):

    # Choices
    FTMN = models.TextChoices(
        'Tamano Comida', 'Pequeno Mediano Grande')
    DSPNL = models.TextChoices('Disponibilidad', 'Si No')

    Id = models.AutoField(primary_key=True)
    name = models.CharField(default="Bollo", max_length=20)
    Imagen = models.ImageField(upload_to='shop/media', blank=False, null=True)
    Tamano = models.CharField(
        max_length=10, choices=FTMN.choices, blank=False, null=True)
    PrecioU = models.CharField(
        max_length=5, blank=False, null=True)
    Disponible = models.CharField(
        max_length=5, choices=DSPNL.choices, blank=False, null=True)
    Created_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = ("Bollo")
        verbose_name_plural = ("Bollos")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Bollo_detail", kwargs={"pk": self.pk})

shop/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from .models import Salchipapa, Empanada, ArepadeHuevo, Carimanola, Bollo
from django.http import JsonResponse
from . import send_whataspp
import datetime
# Create your views here.


def home(request):
    return render(request, 'shop/home.html')


@login_required
def ppage(request):
    if request.method == 'GET':
        salchipapas = Salchipapa.objects.all()
        empanadas = Empanada.objects.all()
        arepasdehuevo = ArepadeHuevo.objects.all()
        carimanolas = Carimanola.objects.all()
        bollos = Bollo.objects.all()
        return render(request, 'shop/princitalpage.html', {"salchipapas": salchipapas, "empanadas": empanadas, "arepasdehuevo": arepasdehuevo, "carimanolas": carimanolas, "bollos": bollos})
    else:
        pass


@login_required
def payment(request):
    salchipapas = Salchipapa.objects.all()
    empanadas = Empanada.objects.all()
    arepasdehuevo = ArepadeHuevo.objects.all()
    carimanolas = Carimanola.objects.all()
    bollos = Bollo.objects.all()
    if request.method == 'GET':
        return render(request, 'shop/payment.html', {"salchipapas": salchipapas, "empanadas": empanadas, "arepasdehuevo": arepasdehuevo, "carimanolas": carimanolas, "bollos": bollos})
    elif request.method == "POST":
        producto = request.POST['productos']
        cantidad = request.POST['cuenta']
        mensaje = ""
        if cantidad == "":
            mensaje = "No se selecciono una cantidad"
        else:
            mensaje = f"Pedido creado exitosamente"
        mensaje_confirm = f"Se creo el pedido con {cantidad} unidades del producto {producto}"
        username = request.user.username
        try:
            whatsapp_body = f"El usuario {username} realizo un pedido con {cantidad} unidades del producto {producto} en la fecha {datetime.date.today()}"
            send_whataspp.SendWhatsapp(whatsapp_body)
            return render(request, 'shop/payment.html', {"cantidad": cantidad, "producto": producto, "confirm": mensaje_confirm, "mensaje": mensaje, "salchipapas": salchipapas, "empanadas": empanadas, "arepasdehuevo": arepasdehuevo, "carimanolas": carimanolas, "bollos": bollos})
        except:
            error = "No se creo el pedido correctamente!"
            return render(request, 'shop/payment.html', {"error": error, "salchipapas": salchipapas, "empanadas": empanadas, "arepasdehuevo": arepasdehuevo, "carimanolas": carimanolas, "bollos": bollos})
    else:
        pass


def singup(request):
    if request.method == 'GET':
        return render(request, 'shop/singup.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            # Create a new User
            try:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password2'])
                user.save()
                django_login(request, user)
                return redirect('shop:ppage')
            except IntegrityError:
                return render(request, 'shop/singup.html', {'form': UserCreationForm(), 'error': 'The username has already been taken. Plese chose a new username'})
        else:
            return render(request, 'shop/singup.html', {'form': UserCreationForm(), 'error': 'Passwords did not match'})


def login(request):
    if request.method == 'GET':
        return render(request, 'shop/login.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'shop/login.html', {'form': AuthenticationForm(), 'error': 'Username and password did not match'})
        else:
            django_login(request, user)
            return redirect('shop:ppage')


@login_required
def logout(request):
    if request.method == 'POST':
        django_logout(request)
        return redirect('shop:home')

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Antojito</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Antojito</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:ppage' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:payment' %}">Payment <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    {% if user.is_authenticated %}
    <span class="navbar-text">
      <li class="nav-item">
        <p>{{ user.username }}</p>
      </li>
      <form action="{% url 'shop:logout'%}" method="POST">
        <button type="submit">Logout</button>
        {% csrf_token %}
      </form>
    </span>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:singup' %}">Sing Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:login' %}">Login</a>
      </li>
    {% endif %}
  </div>
</nav>
    {% block content %}
    {% endblock %}
</body>
</html>

shop/templates/shop/home.html
{% extends 'shop/base.html' %} 
{% block content %}
Home, aqui va el login y registro
{% endblock %}

shop/templates/shop/login.html
{% extends 'shop/base.html' %} 
{% block content %}
<center><h1>Login de usuario</h1></center>
<center><h2>{{ error }}</h2></center>
<form method="POST" action=>
  {{ form.as_p }}
  <button type="submit">Ingresar</button>
  {% csrf_token %}
</form>
{% endblock %}

shop/templates/shop/payment.html
{% extends 'shop/base.html' %}
{% block content %}
<h2>{{ mensaje }}</h2>
<form method="POST" action="">
{% csrf_token %}
<label for="productos">Escoja el producto</label>
<select id="productos" name="productos">
  <option value={% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.name}}{% endfor %}>{% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.name}}{% endfor %}</option>
  <option value={% for carimanola in carimanolas %}{{carimanola.name}}{% endfor %}>{% for carimanola in carimanolas %}{{carimanola.name}}{% endfor %}</option>
  <option value={% for empanada in empanadas %}{{empanada.name}}{% endfor %}>{% for empanada in empanadas %}{{empanada.name}}{% endfor %}</option>
  <option value={% for salchipapa in salchipapas %}{{salchipapa.name}}{% endfor %}>{% for salchipapa in salchipapas %}{{salchipapa.name}}{% endfor %}</option>
  <option value={% for bollo in bollos %}{{bollo.name}}{% endfor %}>{% for bollo in bollos %}{{bollo.name}}{% endfor %}</option>
</select>
<input type="number" name="cuenta">
<input type="submit" value="Crear Pedido">
</form>
{% if mensaje == "Pedido creado exitosamente" %}
  {{ confirm }}
  <a href="https://api.whatsapp.com/send?phone=+573014723047text=Hola+Alyeth+soy+{{ user.username }}+y+pedi+{{ cantidad }}+unidades+de+{{ producto }}">confirmar pedido</a>
{% endif %}
{% endblock %}

shop/templates/shop/princitalpage.html
{% extends 'shop/base.html' %}
{% block content %}
{% for salchipapa in salchipapas %}
<center>
  <h2>{{ salchipapa.name }}</h2>
  <img
    class="img-fluid"
    src="{{ salchipapa.Imagen.url }}"
    width="400"
    height="250"
    alt=""
  />
  <p>Disponible: {{ salchipapa.Disponible }}</p>
  <p>Tamano: {{ salchipapa.Tamano }}</p>
  <p>Precio: ${{ salchipapa.PrecioU }}</p>
{% endfor %}
{% for empanada in empandas %}
<center>
  <h2>{{ empanada.name }}</h2>
  <img
    class="img-fluid"
    src="{{ empanada.Imagen.url }}"
    width="400"
    height="250"
    alt=""
  />
  <p>Disponible: {{ empanada.Disponible }}</p>
  <p>Tamano: {{ empanada.Tamano }}</p>
  <p>Precio: ${{ empanada.PrecioU }}</p>
</center>
{% endfor %}
{% for arepadehuevo in arepasdehuevo %}
<center>
  <h2>{{ arepadehuevo.name }}</h2>
  <img
    class="img-fluid"
    src="{{ arepadehuevo.Imagen.url }}"
    width="400"
    height="250"
    alt=""
  />
  <p>Disponible: {{ arepadehuevo.Disponible }}</p>
  <p>Tamano: {{ arepadehuevo.Tamano }}</p>
  <p>Precio: ${{ arepadehuevo.PrecioU }}</p>
</center>
{% endfor %}
{% for carimanola in carimanolas %}
<center>
  <h2>{{ carimanola.name }}</h2>
  <img
    class="img-fluid"
    src="{{ carimanola.Imagen.url }}"
    width="400"
    height="250"
    alt=""
  />
  <p>Disponible: {{ carimanola.Disponible }}</p>
  <p>Tamano: {{ carimanola.Tamano }}</p>
  <p>Precio: ${{ carimanola.PrecioU }}</p>
</center>
{% endfor %}
{% for bollo in bollos %}
<center>
  <h2>{{ bollo.name }}</h2>
  <img
    class="img-fluid"
    src="{{ bollo.Imagen.url }}"
    width="400"
    height="250"
    alt=""
  />
  <p>Disponible: {{ bollo.Disponible }}</p>
  <p>Tamano: {{ bollo.Tamano }}</p>
  <p>Precio: ${{ bollo.PrecioU }}</p>
</center>
{% endfor %}

<center><h3>Tabla de precios por unidad</h3></center>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Arepa de Huevo</th>
      <th scope="col">Carimanola</th>
      <th scope="col">Empanada</th>
      <th scope="col">Salchipapa</th>
      <th scope="col">Bollo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>{% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.PrecioU}}{% endfor %}</td>
      <td>{% for carimanola in carimanolas %}{{carimanola.PrecioU}}{% endfor %}</td>
      <td>{% for empanada in empanadas %}{{empanada.PrecioU}}{% endfor %}</td>
      <td>{% for salchipapa in salchipapas %}{{salchipapa.PrecioU}}{% endfor %}</td>
      <td>{% for bollo in bollos %}{{bollo.PrecioU}}{% endfor %}</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>{% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.PrecioU|add:arepadehuevo.PrecioU}}{% endfor %}</td>
      <td>{% for carimanola in carimanolas %}{{carimanola.PrecioU|add:carimanola.PrecioU}}{% endfor %}</td>
      <td>{% for empanada in empanadas %}{{empanada.PrecioU|add:empanada.PrecioU}}{% endfor %}</td>
      <td>{% for salchipapa in salchipapas %}{{salchipapa.PrecioU|add:salchipapa.PrecioU}}{% endfor %}</td>
      <td>{% for bollo in bollos %}{{bollo.PrecioU|add:bollo.PrecioU}}{% endfor %}</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>{% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.PrecioU|add:arepadehuevo.PrecioU|add:arepadehuevo.PrecioU}}{% endfor %}</td>
      <td>{% for carimanola in carimanolas %}{{carimanola.PrecioU|add:carimanola.PrecioU|add:carimanola.PrecioU}}{% endfor %}</td>
      <td>{% for empanada in empanadas %}{{empanada.PrecioU|add:empanada.PrecioU|add:empanada.PrecioU}}{% endfor %}</td>
      <td>{% for salchipapa in salchipapas %}{{salchipapa.PrecioU|add:salchipapa.PrecioU|add:salchipapa.PrecioU}}{% endfor %}</td>
      <td>{% for bollo in bollos %}{{bollo.PrecioU|add:bollo.PrecioU|add:bollo.PrecioU}}{% endfor %}</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td>{% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.PrecioU|add:arepadehuevo.PrecioU|add:arepadehuevo.PrecioU|add:arepadehuevo.PrecioU}}{% endfor %}</td>
      <td>{% for carimanola in carimanolas %}{{carimanola.PrecioU|add:carimanola.PrecioU|add:carimanola.PrecioU|add:carimanola.PrecioU}}{% endfor %}</td>
      <td>{% for empanada in empanadas %}{{empanada.PrecioU|add:empanada.PrecioU|add:empanada.PrecioU|add:empanada.PrecioU}}{% endfor %}</td>
      <td>{% for salchipapa in salchipapas %}{{salchipapa.PrecioU|add:salchipapa.PrecioU|add:salchipapa.PrecioU|add:salchipapa.PrecioU}}{% endfor %}</td>
      <td>{% for bollo in bollos %}{{bollo.PrecioU|add:bollo.PrecioU|add:bollo.PrecioU|add:bollo.PrecioU}}{% endfor %}</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td>{% for arepadehuevo in arepasdehuevo %}{{arepadehuevo.PrecioU|add:arepadehuevo.PrecioU|add:arepadehuevo.PrecioU|add:arepadehuevo.PrecioU|add:arepadehuevo.PrecioU}}{% endfor %}</td>
      <td>{% for carimanola in carimanolas %}{{carimanola.PrecioU|add:carimanola.PrecioU|add:carimanola.PrecioU|add:carimanola.PrecioU|add:carimanola.PrecioU}}{% endfor %}</td>
      <td>{% for empanada in empanadas %}{{empanada.PrecioU|add:empanada.PrecioU|add:empanada.PrecioU|add:empanada.PrecioU|add:empanada.PrecioU}}{% endfor %}</td>
      <td>{% for salchipapa in salchipapas %}{{salchipapa.PrecioU|add:salchipapa.PrecioU|add:salchipapa.PrecioU|add:salchipapa.PrecioU|add:salchipapa.PrecioU}}{% endfor %}</td>
      <td>{% for bollo in bollos %}{{bollo.PrecioU|add:bollo.PrecioU|add:bollo.PrecioU|add:bollo.PrecioU|add:bollo.PrecioU}}{% endfor %}</td>
    </tr>
  </tbody>
</table>

<form method="GET" action={% url 'shop:payment' %}>
{% csrf_token %}
<button type="submit" class="btn btn-success">Comprar</button>
</form>
{% endblock %}

shop/templates/shop/singup.html
{% extends 'shop/base.html' %} 
{% block content %}
<center><h1>Registro de usuario</h1></center>
<center><h2>{{ error }}</h2></center>
<form method="POST" action=>
  {{ form.as_p }}
  <button type="submit">Registro</button>
  {% csrf_token %}
</form>
{% endblock %}